# Generated by Django 5.0.6 on 2025-07-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamil', models.IntegerField()),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('social', models.IntegerField()),
                ('total', models.IntegerField()),
                ('average', models.FloatField()),
                ('result', models.BooleanField()),
            ],
        ),
    ]
