# Generated by Django 5.2.4 on 2025-11-10 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_task_student_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='student_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_task', to='students.student'),
        ),
    ]
