# Generated by Django 5.0.6 on 2025-08-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberary', '0002_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
